version: '3.1'

services:

  db:
    image: postgres:alpine3.19
    restart: no
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db_files/db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: no
    networks:
      - app-network
    ports:
      - "8080:8080"

networks:
  app-network:
    driver: bridge
